### ISSUE TITLE
error SignedOutException, for a firestore document that does not require authentication.

### ISSUE THREAD

**Issue by Justus-M** [cachapa/firedart#113]
Firstly huge thanks for this library.

I get the following error when trying to stream a firestore document while the user is not authenticated.

`
Handling error gRPC Error (code: 13, codeName: INTERNAL, message: Error making call: SignedOutException: Attempted to call a protected resource while signed out, details: null, rawResponse: null, trailers: null) using FirestoreGateway._handleError

`

But here is the relevant firestore rule:
    
```
    match /config/{doc} {
      allow read: if true;
    }
```

Here is the full stacktrace

#134    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#135    StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#137    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#138    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#139    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1240:16)
#140    RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1217:5)
#141    RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1231:7)
#142    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#143    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
#144    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
#145    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#146    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#147    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#148    LiveTestWidgetsFlutterBinding.handleDrawFrame (package:flutter_test/src/binding.dart:1758:13)
#149    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#153    _invoke (dart:ui/hooks.dart:144:10)
#154    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#155    _drawFrame (dart:ui/hooks.dart:112:31)
(elided 59 frames from dart:async and package:stack_trace)

**Comment by cachapa** [comment]
Thanks for the report.
On the surface this seems to be a bug, but I'm not currently equipped to test and debug it.

Contributions are welcome though, if you want to take this challenge yourself :-)

**Comment by Justus-M** [comment]
Hi! I did actually see if I could fix it initially but ended up just going for a workaround yesterday.

I wanted to stream the app version number before the user logs in so I can force them to update if necessary (that's what I was doing with flutterfire). I now host a Json file instead, and periodically make an http request to read it.

I just had another look inside the firedart library but couldn't really wrap my head around where this error came from. When you do figure it out, I'll be very curious to understand the fix!

**Comment by vasuravada** [comment]
We got the same issue, Please help us with the quick fix.
